spring:
  application:
    name: badminton-service
  datasource:
    url: jdbc:postgresql://localhost:5432/badminton_db
    username: badminton
    password: badminton_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: badminton
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jooq:
    sql-dialect: POSTGRES

token:
  issuerUrl: http://localhost:${server.port}
  expireTimeInSeconds: 3600
  refreshTokenExpireTimeInDays: 7
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDK6mrxZjg+r4el/BboxzG8JNIU6KGZAYb0Zqpcprr15J8gdynmxAMy88HDwLW4NbHXTdPZY7BU9okpsUbfa2qddXGMBVYqvtiU04dsnFiBKrp6MdqZuFreoxQd3yITKQO1poVh0jta7WuqQqjE14df7vWjBFM/p/LFYGzzTL+hBJHWZNlbktPNEzrP6JUphZJ0pHqN2dcJAMGH1ZezocBs8Xyol/8NStD5WelR4SzMyfw8WqcbfNs44ak6vkj01HwivA7JCbHQL/ukFTgH7I+zz7g3Vim0xbpGnbnfEic1ViM98S+wlHgGlwvcxi268i3uI39BUXWVIAzg32gaVQ0PAgMBAAECggEARKlNxqFwJsX+gIvstJeynJdY/vo4tC1wHQMgYnmIievybGnmI8/vxS32QubSlqKUquYK6WRyJk3F2/XApZkTWnSDF342ygAKCVIKYRYGXK64quBzt9BJ70v/Ypw+S311Y+IVACTDMOFlrRchRHoptKyHMcIk6UVLQL6AH1O5BCKM0xwhSrig4QFpezuLWvpD/6PL577j8MxxiWnR0VIvZoqEjZsguEj0S5zss477xloaHzuljmK6ljrvLFTcgvwCd2Kah/Gb/ZzUhVp8mEoOj3ayWTL6G2wjE4MTUdiCwvfbxIhf2RRTD8ZKo8eGAFk0OnrDoYVuimopgI3myO5vAQKBgQD5to/wZBcTt2s+oRPwrhcO9IFBEmoAHlMw/p7hBE6zx6I9h/eFzUO+GT0mLJn5c+VsXQYJvScCul9T6mR9ybNB4qlY6rm7XmZBqkL8C19wtNqgtTaACyDgu8x/YCLyOPRQStkoWfbPDqsaluas1foq+Q6stIV5GQN0I2b+xlTevQKBgQDQBj03klXvz8/CmA3TIxQFO7UB8AuYTjqm0U1NdaaHAP431IhL9UujcjMD+KEowevx17DpWc6J5Demf/U2ZBriegL9Ct7g19PcTj4UPjqp9+DA4hu+7BC7/l8AoGn7aQzf66hqsUHoFwdX2iphZ2EOLok1OZNIB9USJtnZu+3NuwKBgQCA9FpY1hdkwy/K4/wcKosV2gZ1yECdVwu3HYaGxWavSMTr6a9Vla8KGJaPhDDvtX4g+9kGZnwi2IQqHb1PiD3eJGM329+WdyVve7Gj32umFH9ixrIiZZzQ8aqljMv/MpJYdI64W90tCHIsBQmS792FG6EMZx0WcGhsLWwe3eUuMQKBgFwyR7N3ger1WYlPRuFK7LadDc48C4eHNGt23CH2gMXY5NLtuTKhFtLr7DxYV2Tu/ZmEFP53NRjcMuXyVEW0/E1f8i8gQEO6pEVB0DW8ltd56vzRuaZWjdwkEwr+DbrFhlU/5rbStPkeK7z+DkZ5QQS+D0WtrN8Byadv3KGpru29AoGAeZzQxBpc1X2XxUgqfGq1aD+mu5j8TOCG1og8oZbYhtzq1IAd/qkiXpR9SFqRx3BvLUgqhSd6CS4AZSQ46X6lsBwH4Hd8fUySvWtUtDbQcM918YeDNBWTO4LcKpEiq8UXjPhHgAFN1qsJfwBiJeLxQEIG0ki2zx5zopRhJyqGNeI=
  publicKey: MIIBCgKCAQEAyupq8WY4Pq+HpfwW6McxvCTSFOihmQGG9GaqXKa69eSfIHcp5sQDMvPBw8C1uDWx103T2WOwVPaJKbFG32tqnXVxjAVWKr7YlNOHbJxYgSq6ejHambha3qMUHd8iEykDtaaFYdI7Wu1rqkKoxNeHX+71owRTP6fyxWBs80y/oQSR1mTZW5LTzRM6z+iVKYWSdKR6jdnXCQDBh9WXs6HAbPF8qJf/DUrQ+VnpUeEszMn8PFqnG3zbOOGpOr5I9NR8IrwOyQmx0C/7pBU4B+yPs8+4N1YptMW6Rp253xInNVYjPfEvsJR4BpcL3MYtuvIt7iN/QVF1lSAM4N9oGlUNDwIDAQAB

logging:
  level:
    root: INFO

telegram:
  bot:
    token: 7685244546:AAH98XjAimV90G3eo8fH8AKkQ4ZkkzQYBfM